### PR TITLE
Replace window.alert and window.confirm with custom modal

### LINKED ISSUE #30: Move all functions declared outside Component body to a utility file
The code could be more readable and less congested if we moved all utility functions such as [this](https://github.com/the-collab-lab/tcl-19-smart-shopping-list/blob/main/src/components/ItemsList.js#L18-L31) to a file dedicated for such functions and are then imported wherever they are needed. 

I suggest we create a `utility.js` file in directory named `utils` in the `src` folder  where we declare all utility functions. 
It would also be  better  to export an instance of `shoppingList`  collection  and `arrayUnion`  utility function from the `lib` directory  instead of exporting `firebase` instance and then creating  an instance of `firestore` collection in every component which subscribes to the database.  Doing `firebase.firestore().collection('shopping_list')` once  in `lib` directory makes the code more maintainable and neat rather than doing it in multiple places.

AC
1. There should be a `utils` directory in the `src` folder
2. There should be `utils.js` file or file(s) with appropriate name(s) holding all the utility functions including those currently in `sortingFunctions.js`
3. Export an instance of the firebase collection from the `lib` directory. The same can be done for `arrayUnion` utility function.

### LINKED ISSUE #36: Add Open Graph Protocol and SEO meta tags
To make the app shareable on social media and optimize it for search engines, there is need to add Open Graph Protocol and SEO meta tags. It is also important to add an appropriate title with app logo appearing beside it so that the app is recognizable instead of having the react logo on the browser tab.

**Title**

Right now we have something like this as our title
image

After, we must have something similar to this as our title
image

**OGP meta tags**

Right now, this is how our app looks when shared on slack
image

After, we should have something similar to this but for the smart shopping app.
image

**SEO**

`description` meta tag should have appropriate text  instead of  the text which comes with CRA.

### LINKED ISSUE #37: #18 Create custom modal component for the project
## Build a custom modal that will be used in place of the browser's default "alert" to tell the users the state of their operations.

**ACs:**

* A modal component is built that accepts props - "message" according to the component its being displayed.
* The modal component is imported into the AddItems component and used in place of the Web API "alert".
* The modal component is imported into the ItemsList component and used in place of the Web API "alert".
* The modal component is imported into the `Home` component and used for alerting the client instead of `window.alert`.

### LINKED ISSUE #40: Make Modals Accessible
Ensure that the custom modals created are accessible:

- Aria attributes included where appropriate
- Modal tab sequence is correct when modal is displayed
- When modal is open, the focus is correct (on the OK or similar button)
- When the modal closes, the focus returns to the element that invoked the modal

### LINKED ISSUE #41: useCollectionData hook reads from firestore on every keystroke when entering token on home page
**Summary**

When a user is entering a token to join an existing list, the `onChange` event handler of the `input` field  updates the value of `existingToken` variable in state. The value of `existingToken` which changes on every keystroke as the user enters a token is also used for making a query from the `firestore` database(DB) using `useCollectionData` hook. This therefore means on every character entry, `react-firebase-hooks` will have to read from the database. It is inefficient to query the DB for the existence of a token when a user has not yet finished entering it given the fact that  there is a maximum number of document reads or writes you can make per day and  billing is done based on the number of reads/writes to the DB as well. We only need to read from the DB if a user submits the token. 

**Steps to reproduce**

To reproduce the issue,
- Pull the `jm-cu-modal-component` branch and start the app on local host using `npm run start`
- Start entering in the `input` field

**Expected results**

The DB is queried only after the user has finished entering token and submitted the `form`.

**Actual results**

- Each time you enter a character, loading spinner will appear on the screen and the `input` field will lose focus
- The loading spinner is rendered if the `loading` variable returned by `useCollectionData` is `true`. `loading` is `true` only if the DB is being queried.

**Environment**

N/A

### LINKED ISSUE #43: Token entered with leading or trailing space is rejected when joining existing list
**Summary**

When a user enters a token to join an existing list with leading or trailing space, the token is rejected.

**Steps to reproduce**

To reproduce the issue,
Navigate to the deployed app on netlify or localhost. Enter an existing token with leading space or trailing space. The token will be rejected.

**Expected results**

The app should accept a token if a user adds a space at the beginning of the token or at the end of the token.

**Actual results**

The app doesn't accept a token if a user adds a space at the beginning of the token or at the end of the token.

**Environment**

N/A

### PR DESCRIPTION
**Pull request by nibble0101**
## Description
- This code replaces `window.confirm` and `window.alert` with custom modal on all pages.
- Moved all utility functions to their own directory.
- Fixed bug of reading from `firestore` before user completes entering an existing token.
- Fixed bug of rejecting existing token when entered with leading or trailing white space.
- Modals are accessible - aria labels have been added, along with the correct focus and tab order when the modal is open and closed.

## Related Issue

Closes #30 
Closes #37 
Closes #41 
Closes #43 
Closes #40 
## Acceptance Criteria

- `window.confirm` and `window.alert` should be replaced with custom modal
- All utility functions must be in their own directory
- Check if token entered by a user exists only after the user completes entering it
- App shouldn't reject existing token entered with leading or trailing spaces.
- Aria attributes included within modals where appropriate
- Modal tab sequence is correct when modal is displayed
- When modal is open, the focus is correct (on the OK or similar button)
- When the modal closes, the focus returns to the element that invoked the modal
## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓ | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
| ✓  | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

### Before

image

### After

image

## Testing Steps / QA Criteria

- Pull this branch from gitHub using `git pull origin jm-cu-modal-component`
- Start the app on `localhost` using `npm run start`
- Try deleting an item from shopping list. There must be a prompt on a custom modal
- Try adding an item to shopping list before entering item name. A custom modal should be displayed with a message.
- Navigate to home page. Enter a non-existent token. You should see a modal with a message.

### CODE REVIEW

File: src/components/ConfirmDeleteModal.js [hunk 1]
```diff
@@ -0,0 +1,65 @@
+import React from 'react';
+
+export default function ConfirmDeleteModal({
```
Comment (YuriDevAT) [inline src/components/ConfirmDeleteModal.js:3]: for consistency reasons for components it would be better to move the export default to the end of the function

File: src/components/Home.js [hunk 2]
```diff
@@ -20,29 +22,74 @@ const Home = () => {
...
-  );
-
   const submitToken = (e) => {
     e.preventDefault();
 
-    if (existingToken === '') {
-      alert('Please enter a token...');
+    if (existingToken.trim() === '') {
+      setShowModal(true);
+      setModalMessage('Please enter a token');
```
Comment (YuriDevAT) [inline src/components/Home.js:30]: There seems to be a difference in loading when I do not have a token and click join the list and inserting a wrong token. The first one it seems, there is no loading, and the modal just appears, while by the latter the whole page reloads.

File: src/components/ItemsList.js [hunk 3]
```diff
@@ -1,49 +1,45 @@
...
+  getShoppingItemBackgroundStyles,
+  wasItemPurchasedWithinLastOneDay,
+  getDaysBetweenCurrentAndPreviousPurchase,
+} from '../utils/utility-functions';
 import AddItemButton from './AddItemButton';
 import { ReactComponent as TrashBin } from '../img/trash-alt-regular.svg';
 import { ReactComponent as HomeIcon } from '../img/home-solid.svg';
 import spinner from '../img/spinner-3.gif';
+import ConfirmDeleteModal from './ConfirmDeleteModal';
 import '../index.css';
```
Comment (YuriDevAT) [inline src/components/ItemsList.js:20]: I think there is no need for importing index.css here since it is in the index.js

File: src/components/Modal.js [hunk 4]
```diff
@@ -0,0 +1,44 @@
+import React from 'react';
+
+export default function Modal({ message, showModal, setShowModal }) {
```
Comment (YuriDevAT) [inline src/components/Modal.js:3]: for consistency reasons for components it would be better to move the export default to the end of the function

**Review by YuriDevAT — APPROVED** [review]
Great work on cleaning up our code, it looks so well structured now. The modals look so great! I really like the favicon 😄 Maybe I will find something which would fit more to our app style.
All in all really great work here, thank you so much. I have only made a few suggestions.

File: src/utils/utility-functions.js [hunk 5]
```diff
@@ -1,6 +1,24 @@
...
+) => {
+  const oneDayInMilliseconds = 24 * 60 * 60 * 1000;
+  return (currentPurchaseDate - previousPurchaseDate) / oneDayInMilliseconds;
+};
+
+export const normalizeString = (str) => {
+  const nonWordCharactersAndUnderscores = /[\W_]/g;
+  return str.toLowerCase().replace(nonWordCharactersAndUnderscores, '');
+};
+
```
Comment (Lukabaramishvili) [inline src/utils/utility-functions.js:19]: Wow! I love everything about this file. Such an amazing abstraction. 💯 🥇

File: src/components/ConfirmDeleteModal.js [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
```
Comment (Lukabaramishvili) [inline src/components/ConfirmDeleteModal.js:3]: This modal is so well architected! Brilliant work 👏

File: src/components/Modal.js [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+                      ×
+                    </span>
+                  </button>
+                </div>
+                <div className="relative p-6 flex-auto">
+                  <p
+                    className="my-4 text-gray-600 text-lg leading-relaxed"
+                    id="dialog-message"
+                  >
+                    {message}
```
Comment (Lukabaramishvili) [inline src/components/Modal.js:34]: I love how reusable this modal is. And fully accessible. 👏

**Review by Lukabaramishvili — APPROVED** [review]
So much work was done here. Just fantastic work.
1. Modals are fully accessible and reusable in terms of displaying different messages 👏
2. Some code abstractions in the utils file 🙌
3. Overall, super well-architected HTML and codebase 🚀 

Thank you so much for doing brilliant work in this PR 💫

**Review by rb50 — APPROVED** [review]
I love the modal design- and it’s great that the element is reusable for the add item modal with the different messages. 😊
